name: Deploy to Compute Engine

on:
  push:
    branches:
      - main  # Change this to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3. Deploy to Compute Engine
    - name: Deploy to GCE
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_SSH_USER }}@${{ secrets.GCE_INSTANCE_IP }} << 'EOF'
          set -e
          # Navigate to your project directory or clone the repository if not present
          cd backend || git clone git@github.com:your-username/your-repo.git backend
          cd backend

          # Pull latest changes
          git reset --hard
          git pull origin main

          # Run any additional setup commands (e.g., npm install, restart services)
          # Example: Restarting a Node.js application
          pm2 restart backend || npm run start
        EOF
