name: Deploy to Compute Engine

on:
  push:
    branches:
      - master  # Change this to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3. Deploy to Compute Engine
    - name: Deploy to GCE
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCE_SSH_USER }}@${{ secrets.GCE_INSTANCE_IP }} << 'EOF'
          set -e

          # Navigate to your project directory or clone the repository if not present
          if [ ! -d "backend" ]; then
            git clone https://github.com/bmmasaputra/vm-workflow.git backend
          fi
          cd backend

          # Pull the latest changes
          git reset --hard
          git pull origin master

          # Check if 'node_modules' directory exists, install dependencies if missing
          if [ ! -d "node_modules" ]; then
            echo "node_modules directory not found. Installing dependencies..."
            npm install
            npm install pm2@latest -g
          fi

          # Run any additional setup commands (e.g., restart services)
          # Example: Restarting a Node.js application
          pm2 restart backend || pm2 start app.js
        EOF
